coverage:
  status:
    project:
      default:
        target: 60%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: false

ignore:
  - "**/*_test.go"
  - "**/benchmark/**"
  - "**/vendor/**"
  - "internal/proto/**"
