#!/usr/bin/env bash
# server.sh — Provisioning for the Pheromone server VM
# ADR-012: Vagrant Testing Environment
#
# Configures the server VM:
#   - Starts etcd via docker compose (reuses project docker-compose.yml)
#   - Verifies etcd health
#   - Builds pheromone-server binary
#   - Writes a default UI configuration file
#   - Installs and starts the pheromone-ui systemd service (management UI)
#
# Environment variables (set by Vagrantfile):
#   SERVER_IP  — Server VM private network IP (e.g., "192.168.56.10")
#   UI_PORT    — Management UI HTTP port (e.g., "8081")
#   GO_VERSION — Go toolchain version

set -euo pipefail

SERVER_IP="${SERVER_IP:-192.168.56.10}"
UI_PORT="${UI_PORT:-8081}"
PROJECT_DIR="/home/vagrant/pheromone"
ETCD_HEALTH_URL="http://${SERVER_IP}:2379/health"
UI_HEALTH_URL="http://127.0.0.1:${UI_PORT}/api/v1/health"
ETCD_RETRY_SECS=30
UI_CONFIG_DIR="/etc/pheromone/server"
UI_BINARY="/usr/local/bin/pheromone-server"
UI_SERVICE="pheromone-ui"

log() { echo "[server.sh] $*"; }

export PATH="/usr/local/go/bin:${PATH}"

# ── Verify Go is available ───────────────────────────────────────────────────
if ! command -v go &>/dev/null; then
  echo "[server.sh] ERROR: Go not found. Ensure common.sh ran first." >&2
  exit 1
fi
log "Go version: $(go version)"

# ── etcd via Docker Compose ──────────────────────────────────────────────────
if [[ ! -f "${PROJECT_DIR}/docker-compose.yml" ]]; then
  log "WARNING: ${PROJECT_DIR}/docker-compose.yml not found — skipping etcd start."
  log "Mount the project directory and re-provision to start etcd."
else
  log "Starting etcd via docker compose..."
  cd "${PROJECT_DIR}"
  docker compose up -d etcd 2>&1 || docker-compose up -d etcd 2>&1
  log "Waiting up to ${ETCD_RETRY_SECS}s for etcd to become healthy..."
  for i in $(seq 1 "${ETCD_RETRY_SECS}"); do
    if curl -sf "${ETCD_HEALTH_URL}" > /dev/null 2>&1; then
      log "etcd is healthy at ${ETCD_HEALTH_URL}"
      break
    fi
    if [[ "${i}" -eq "${ETCD_RETRY_SECS}" ]]; then
      log "WARNING: etcd did not become healthy after ${ETCD_RETRY_SECS}s."
      log "Check: docker compose logs etcd"
    fi
    sleep 1
  done
fi

# ── Build pheromone-server binary ────────────────────────────────────────────
SERVER_CMD_PATH="${PROJECT_DIR}/cmd/pheromone-server/main.go"
if [[ -f "${SERVER_CMD_PATH}" ]]; then
  log "Building pheromone-server binary..."
  cd "${PROJECT_DIR}"
  go build -o "${UI_BINARY}" ./cmd/pheromone-server/
  log "pheromone-server installed to ${UI_BINARY}"
  "${UI_BINARY}" --help 2>/dev/null | head -5 || true
else
  log "pheromone-server (${SERVER_CMD_PATH}) not found — skipping build."
fi

# ── Write management UI configuration ────────────────────────────────────────
if [[ -x "${UI_BINARY}" ]]; then
  log "Writing management UI configuration to ${UI_CONFIG_DIR}/ui.yaml..."
  mkdir -p "${UI_CONFIG_DIR}"

  # Generate a strong random secret key for token signing
  UI_SECRET=$(openssl rand -hex 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-f0-9' | head -c 64)

  # Generate a password hash for the default admin:admin account using the binary
  ADMIN_HASH=$("${UI_BINARY}" ui hash-password admin 2>/dev/null || echo "sha256:vagrant:8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918")

  cat > "${UI_CONFIG_DIR}/ui.yaml" <<UICFG
# Pheromone management UI configuration
# Generated by Vagrant provisioning — development environment defaults
ui:
  enabled: true
  address: "0.0.0.0"
  port: ${UI_PORT}
  secret_key: "${UI_SECRET}"
  token_ttl: 24h
  allowed_origins:
    - "*"
  users:
    - username: admin
      password_hash: "${ADMIN_HASH}"
      role: admin
    - username: viewer
      password_hash: "$(${UI_BINARY} ui hash-password viewer 2>/dev/null || echo 'sha256:vagrant2:sha256placeholder')"
      role: viewer
UICFG
  chmod 600 "${UI_CONFIG_DIR}/ui.yaml"
  log "UI config written (admin/admin, viewer/viewer)"
fi

# ── Install pheromone-ui systemd service ─────────────────────────────────────
if [[ -x "${UI_BINARY}" ]]; then
  log "Installing ${UI_SERVICE} systemd service..."

  cat > "/etc/systemd/system/${UI_SERVICE}.service" <<UNIT
[Unit]
Description=Pheromone Management UI
Documentation=https://github.com/abuxton/pheromone
After=network.target

[Service]
Type=simple
User=vagrant
Group=vagrant
ExecStart=${UI_BINARY} serve --config-path ${UI_CONFIG_DIR} --ui-port ${UI_PORT}
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=${UI_SERVICE}
Environment=PATH=/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

[Install]
WantedBy=multi-user.target
UNIT

  systemctl daemon-reload
  systemctl enable "${UI_SERVICE}"
  systemctl restart "${UI_SERVICE}"

  log "Waiting up to 15s for management UI to become healthy..."
  for i in $(seq 1 15); do
    if curl -sf "${UI_HEALTH_URL}" > /dev/null 2>&1; then
      log "Management UI is healthy at ${UI_HEALTH_URL}"
      break
    fi
    if [[ "${i}" -eq 15 ]]; then
      log "WARNING: Management UI did not respond after 15s. Check: journalctl -u ${UI_SERVICE}"
    fi
    sleep 1
  done
else
  log "Skipping systemd service installation (binary not built)."
fi

# ── Helper commands (server VM) ─────────────────────────────────────────────
log "Installing server helper commands..."

cat > /usr/local/bin/ph-etcd-health <<SCRIPT
#!/usr/bin/env bash
curl -sf "http://${SERVER_IP}:2379/health"
SCRIPT

cat > /usr/local/bin/ph-etcd-up <<SCRIPT
#!/usr/bin/env bash
set -euo pipefail
cd /home/vagrant/pheromone
docker compose up -d etcd
SCRIPT

cat > /usr/local/bin/ph-etcd-down <<SCRIPT
#!/usr/bin/env bash
set -euo pipefail
cd /home/vagrant/pheromone
docker compose stop etcd
SCRIPT

cat > /usr/local/bin/ph-test-etcd <<SCRIPT
#!/usr/bin/env bash
set -euo pipefail
export PATH="/usr/local/go/bin:\${PATH}"
export ETCD_ENDPOINT="http://${SERVER_IP}:2379"
cd /home/vagrant/pheromone
exec go test -v ./benchmark/... -run 'TestEtcd|TestHybrid|TestServerRecoveryTime'
SCRIPT

cat > /usr/local/bin/ph-ui-health <<SCRIPT
#!/usr/bin/env bash
# Check the management UI health endpoint and print a summary
URL="http://127.0.0.1:${UI_PORT}/api/v1/health"
echo "Checking UI health at \${URL} ..."
if curl -sf "\${URL}" 2>/dev/null | python3 -m json.tool 2>/dev/null; then
  echo ""
  echo "UI is healthy. Open http://localhost:${UI_PORT} in your host browser."
else
  echo "UI health check failed. Service status:"
  systemctl status ${UI_SERVICE} --no-pager -l || true
fi
SCRIPT

cat > /usr/local/bin/ph-ui-status <<SCRIPT
#!/usr/bin/env bash
systemctl status ${UI_SERVICE} --no-pager -l
SCRIPT

cat > /usr/local/bin/ph-ui-logs <<SCRIPT
#!/usr/bin/env bash
journalctl -u ${UI_SERVICE} -f --no-pager "\$@"
SCRIPT

cat > /usr/local/bin/ph-ui-restart <<SCRIPT
#!/usr/bin/env bash
systemctl restart ${UI_SERVICE}
echo "${UI_SERVICE} restarted."
systemctl status ${UI_SERVICE} --no-pager -l
SCRIPT

chmod +x \
  /usr/local/bin/ph-etcd-health \
  /usr/local/bin/ph-etcd-up \
  /usr/local/bin/ph-etcd-down \
  /usr/local/bin/ph-test-etcd \
  /usr/local/bin/ph-ui-health \
  /usr/local/bin/ph-ui-status \
  /usr/local/bin/ph-ui-logs \
  /usr/local/bin/ph-ui-restart

log "Server provisioning complete."
log "  etcd:         curl ${ETCD_HEALTH_URL}"
log "  Management UI: http://localhost:${UI_PORT}  (forwarded from VM port ${UI_PORT})"
log "  Credentials:  admin / admin  (or viewer / viewer)"
log "  SSH: vagrant ssh server"

