// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: pheromone/v1/action_events.proto

package pheromone_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ActionEventService_ReportActionEvent_FullMethodName   = "/pheromone.v1.ActionEventService/ReportActionEvent"
	ActionEventService_ReportDeliveryEvent_FullMethodName = "/pheromone.v1.ActionEventService/ReportDeliveryEvent"
	ActionEventService_StreamHookConfig_FullMethodName    = "/pheromone.v1.ActionEventService/StreamHookConfig"
)

// ActionEventServiceClient is the client API for ActionEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ActionEventService provides RPCs for agents to report post-action outcomes and for the
// server to stream registered hook configurations back to agents (ADR-011).
type ActionEventServiceClient interface {
	// ReportActionEvent allows an agent to report the outcome of a skill execution to the server.
	// The server evaluates registered hooks and dispatches notifications as appropriate.
	ReportActionEvent(ctx context.Context, in *ActionEvent, opts ...grpc.CallOption) (*ActionEventAck, error)
	// ReportDeliveryEvent allows an agent to report a package/artifact delivery outcome.
	ReportDeliveryEvent(ctx context.Context, in *PackageDeliveryEvent, opts ...grpc.CallOption) (*DeliveryEventAck, error)
	// StreamHookConfig streams the hook configurations registered for this agent back to
	// the agent at connection time so it can fire direct hooks without a server round-trip.
	StreamHookConfig(ctx context.Context, in *HookConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HookConfig], error)
}

type actionEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewActionEventServiceClient(cc grpc.ClientConnInterface) ActionEventServiceClient {
	return &actionEventServiceClient{cc}
}

func (c *actionEventServiceClient) ReportActionEvent(ctx context.Context, in *ActionEvent, opts ...grpc.CallOption) (*ActionEventAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionEventAck)
	err := c.cc.Invoke(ctx, ActionEventService_ReportActionEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionEventServiceClient) ReportDeliveryEvent(ctx context.Context, in *PackageDeliveryEvent, opts ...grpc.CallOption) (*DeliveryEventAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliveryEventAck)
	err := c.cc.Invoke(ctx, ActionEventService_ReportDeliveryEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *actionEventServiceClient) StreamHookConfig(ctx context.Context, in *HookConfigRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[HookConfig], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ActionEventService_ServiceDesc.Streams[0], ActionEventService_StreamHookConfig_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[HookConfigRequest, HookConfig]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActionEventService_StreamHookConfigClient = grpc.ServerStreamingClient[HookConfig]

// ActionEventServiceServer is the server API for ActionEventService service.
// All implementations should embed UnimplementedActionEventServiceServer
// for forward compatibility.
//
// ActionEventService provides RPCs for agents to report post-action outcomes and for the
// server to stream registered hook configurations back to agents (ADR-011).
type ActionEventServiceServer interface {
	// ReportActionEvent allows an agent to report the outcome of a skill execution to the server.
	// The server evaluates registered hooks and dispatches notifications as appropriate.
	ReportActionEvent(context.Context, *ActionEvent) (*ActionEventAck, error)
	// ReportDeliveryEvent allows an agent to report a package/artifact delivery outcome.
	ReportDeliveryEvent(context.Context, *PackageDeliveryEvent) (*DeliveryEventAck, error)
	// StreamHookConfig streams the hook configurations registered for this agent back to
	// the agent at connection time so it can fire direct hooks without a server round-trip.
	StreamHookConfig(*HookConfigRequest, grpc.ServerStreamingServer[HookConfig]) error
}

// UnimplementedActionEventServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActionEventServiceServer struct{}

func (UnimplementedActionEventServiceServer) ReportActionEvent(context.Context, *ActionEvent) (*ActionEventAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportActionEvent not implemented")
}
func (UnimplementedActionEventServiceServer) ReportDeliveryEvent(context.Context, *PackageDeliveryEvent) (*DeliveryEventAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportDeliveryEvent not implemented")
}
func (UnimplementedActionEventServiceServer) StreamHookConfig(*HookConfigRequest, grpc.ServerStreamingServer[HookConfig]) error {
	return status.Error(codes.Unimplemented, "method StreamHookConfig not implemented")
}
func (UnimplementedActionEventServiceServer) testEmbeddedByValue() {}

// UnsafeActionEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActionEventServiceServer will
// result in compilation errors.
type UnsafeActionEventServiceServer interface {
	mustEmbedUnimplementedActionEventServiceServer()
}

func RegisterActionEventServiceServer(s grpc.ServiceRegistrar, srv ActionEventServiceServer) {
	// If the following call panics, it indicates UnimplementedActionEventServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ActionEventService_ServiceDesc, srv)
}

func _ActionEventService_ReportActionEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionEventServiceServer).ReportActionEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionEventService_ReportActionEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionEventServiceServer).ReportActionEvent(ctx, req.(*ActionEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionEventService_ReportDeliveryEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PackageDeliveryEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActionEventServiceServer).ReportDeliveryEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ActionEventService_ReportDeliveryEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActionEventServiceServer).ReportDeliveryEvent(ctx, req.(*PackageDeliveryEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _ActionEventService_StreamHookConfig_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HookConfigRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ActionEventServiceServer).StreamHookConfig(m, &grpc.GenericServerStream[HookConfigRequest, HookConfig]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ActionEventService_StreamHookConfigServer = grpc.ServerStreamingServer[HookConfig]

// ActionEventService_ServiceDesc is the grpc.ServiceDesc for ActionEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ActionEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pheromone.v1.ActionEventService",
	HandlerType: (*ActionEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportActionEvent",
			Handler:    _ActionEventService_ReportActionEvent_Handler,
		},
		{
			MethodName: "ReportDeliveryEvent",
			Handler:    _ActionEventService_ReportDeliveryEvent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamHookConfig",
			Handler:       _ActionEventService_StreamHookConfig_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pheromone/v1/action_events.proto",
}
