// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pheromone/v1/action_events.proto

package pheromone_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ActionEvent carries the outcome of a skill execution (ADR-011).
type ActionEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id identifies the agent that executed the skill.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// twin_id is the target twin for the executed action.
	TwinId string `protobuf:"bytes,2,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	// skill_name names the skill that was executed, e.g. "config-enforce", "digital-twin".
	SkillName string `protobuf:"bytes,3,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	// action_type describes the specific operation, e.g. "package-install", "config-apply", "rollback".
	ActionType string `protobuf:"bytes,4,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	// outcome is one of "success", "failure", or "partial".
	Outcome string `protobuf:"bytes,5,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// detail is a human-readable summary of the outcome.
	Detail string `protobuf:"bytes,6,opt,name=detail,proto3" json:"detail,omitempty"`
	// timestamp_unix is the time the action completed, in seconds since the Unix epoch.
	TimestampUnix int64 `protobuf:"varint,7,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	// trace_id correlates this event with the corresponding TelemetryStream trace.
	TraceId string `protobuf:"bytes,8,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// labels contains arbitrary key-value context for this event.
	Labels        map[string]string `protobuf:"bytes,9,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionEvent) Reset() {
	*x = ActionEvent{}
	mi := &file_pheromone_v1_action_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionEvent) ProtoMessage() {}

func (x *ActionEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_action_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionEvent.ProtoReflect.Descriptor instead.
func (*ActionEvent) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_action_events_proto_rawDescGZIP(), []int{0}
}

func (x *ActionEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ActionEvent) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *ActionEvent) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *ActionEvent) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ActionEvent) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *ActionEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ActionEvent) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *ActionEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ActionEvent) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// ActionEventAck acknowledges receipt of an ActionEvent.
type ActionEventAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// received indicates whether the server successfully persisted the event.
	Received bool `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	// hooks_triggered is the number of server-side hooks that were fired in response to this event.
	HooksTriggered int32 `protobuf:"varint,2,opt,name=hooks_triggered,json=hooksTriggered,proto3" json:"hooks_triggered,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ActionEventAck) Reset() {
	*x = ActionEventAck{}
	mi := &file_pheromone_v1_action_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionEventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionEventAck) ProtoMessage() {}

func (x *ActionEventAck) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_action_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionEventAck.ProtoReflect.Descriptor instead.
func (*ActionEventAck) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_action_events_proto_rawDescGZIP(), []int{1}
}

func (x *ActionEventAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

func (x *ActionEventAck) GetHooksTriggered() int32 {
	if x != nil {
		return x.HooksTriggered
	}
	return 0
}

// PackageDeliveryEvent carries structured metadata about a package/artifact delivery (ADR-011).
type PackageDeliveryEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id identifies the agent that performed the delivery.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// twin_id is the OS or workload twin that was updated.
	TwinId string `protobuf:"bytes,2,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	// package_name is the name of the package, e.g. "nginx".
	PackageName string `protobuf:"bytes,3,opt,name=package_name,json=packageName,proto3" json:"package_name,omitempty"`
	// package_version is the version of the package, e.g. "1.24.0-1ubuntu1".
	PackageVersion string `protobuf:"bytes,4,opt,name=package_version,json=packageVersion,proto3" json:"package_version,omitempty"`
	// action is one of "install", "upgrade", or "remove".
	Action string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	// outcome is one of "success" or "failure".
	Outcome string `protobuf:"bytes,6,opt,name=outcome,proto3" json:"outcome,omitempty"`
	// error_detail is populated on failure and contains a description of the error.
	ErrorDetail string `protobuf:"bytes,7,opt,name=error_detail,json=errorDetail,proto3" json:"error_detail,omitempty"`
	// timestamp_unix is the time the delivery completed, in seconds since the Unix epoch.
	TimestampUnix int64 `protobuf:"varint,8,opt,name=timestamp_unix,json=timestampUnix,proto3" json:"timestamp_unix,omitempty"`
	// trace_id correlates this event with the corresponding TelemetryStream trace.
	TraceId       string `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageDeliveryEvent) Reset() {
	*x = PackageDeliveryEvent{}
	mi := &file_pheromone_v1_action_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageDeliveryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageDeliveryEvent) ProtoMessage() {}

func (x *PackageDeliveryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_action_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageDeliveryEvent.ProtoReflect.Descriptor instead.
func (*PackageDeliveryEvent) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_action_events_proto_rawDescGZIP(), []int{2}
}

func (x *PackageDeliveryEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *PackageDeliveryEvent) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *PackageDeliveryEvent) GetPackageName() string {
	if x != nil {
		return x.PackageName
	}
	return ""
}

func (x *PackageDeliveryEvent) GetPackageVersion() string {
	if x != nil {
		return x.PackageVersion
	}
	return ""
}

func (x *PackageDeliveryEvent) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *PackageDeliveryEvent) GetOutcome() string {
	if x != nil {
		return x.Outcome
	}
	return ""
}

func (x *PackageDeliveryEvent) GetErrorDetail() string {
	if x != nil {
		return x.ErrorDetail
	}
	return ""
}

func (x *PackageDeliveryEvent) GetTimestampUnix() int64 {
	if x != nil {
		return x.TimestampUnix
	}
	return 0
}

func (x *PackageDeliveryEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

// DeliveryEventAck acknowledges receipt of a PackageDeliveryEvent.
type DeliveryEventAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// received indicates whether the server successfully persisted the delivery event.
	Received      bool `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliveryEventAck) Reset() {
	*x = DeliveryEventAck{}
	mi := &file_pheromone_v1_action_events_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveryEventAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveryEventAck) ProtoMessage() {}

func (x *DeliveryEventAck) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_action_events_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveryEventAck.ProtoReflect.Descriptor instead.
func (*DeliveryEventAck) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_action_events_proto_rawDescGZIP(), []int{3}
}

func (x *DeliveryEventAck) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

// HookConfigRequest is sent by an agent to request its applicable hook configurations.
type HookConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id identifies the requesting agent.
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookConfigRequest) Reset() {
	*x = HookConfigRequest{}
	mi := &file_pheromone_v1_action_events_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookConfigRequest) ProtoMessage() {}

func (x *HookConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_action_events_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookConfigRequest.ProtoReflect.Descriptor instead.
func (*HookConfigRequest) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_action_events_proto_rawDescGZIP(), []int{4}
}

func (x *HookConfigRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// HookConfig represents a single registered post-action hook (ADR-011).
type HookConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hook_id is a unique identifier for this hook.
	HookId string `protobuf:"bytes,1,opt,name=hook_id,json=hookId,proto3" json:"hook_id,omitempty"`
	// scope_agent_id scopes the hook to a specific agent; use "*" for fleet-wide hooks.
	ScopeAgentId string `protobuf:"bytes,2,opt,name=scope_agent_id,json=scopeAgentId,proto3" json:"scope_agent_id,omitempty"`
	// scope_twin_id scopes the hook to a specific twin; use "*" for any twin.
	ScopeTwinId string `protobuf:"bytes,3,opt,name=scope_twin_id,json=scopeTwinId,proto3" json:"scope_twin_id,omitempty"`
	// scope_skill scopes the hook to a specific skill; use "*" for any skill.
	ScopeSkill string `protobuf:"bytes,4,opt,name=scope_skill,json=scopeSkill,proto3" json:"scope_skill,omitempty"`
	// event_type filters the hook to "action", "delivery", or "*" for any event type.
	EventType string `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// outcome_filter restricts the hook to "success", "failure", or "*" for any outcome.
	OutcomeFilter string `protobuf:"bytes,6,opt,name=outcome_filter,json=outcomeFilter,proto3" json:"outcome_filter,omitempty"`
	// destination describes where and how to deliver notifications for this hook.
	Destination   *NotificationDestination `protobuf:"bytes,7,opt,name=destination,proto3" json:"destination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookConfig) Reset() {
	*x = HookConfig{}
	mi := &file_pheromone_v1_action_events_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookConfig) ProtoMessage() {}

func (x *HookConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_action_events_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookConfig.ProtoReflect.Descriptor instead.
func (*HookConfig) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_action_events_proto_rawDescGZIP(), []int{5}
}

func (x *HookConfig) GetHookId() string {
	if x != nil {
		return x.HookId
	}
	return ""
}

func (x *HookConfig) GetScopeAgentId() string {
	if x != nil {
		return x.ScopeAgentId
	}
	return ""
}

func (x *HookConfig) GetScopeTwinId() string {
	if x != nil {
		return x.ScopeTwinId
	}
	return ""
}

func (x *HookConfig) GetScopeSkill() string {
	if x != nil {
		return x.ScopeSkill
	}
	return ""
}

func (x *HookConfig) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HookConfig) GetOutcomeFilter() string {
	if x != nil {
		return x.OutcomeFilter
	}
	return ""
}

func (x *HookConfig) GetDestination() *NotificationDestination {
	if x != nil {
		return x.Destination
	}
	return nil
}

// NotificationDestination describes a target for hook dispatch (ADR-011).
type NotificationDestination struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type identifies the destination protocol: "http-webhook", "slack", "email", or "log".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// url is the webhook URL or email address for this destination.
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// headers contains custom HTTP headers to include when dispatching, e.g. authorization tokens.
	Headers map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// timeout_seconds is the per-dispatch HTTP timeout; default is 10.
	TimeoutSeconds int32 `protobuf:"varint,4,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	// max_retries is the maximum number of retry attempts on failure; default is 3.
	MaxRetries    int32 `protobuf:"varint,5,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationDestination) Reset() {
	*x = NotificationDestination{}
	mi := &file_pheromone_v1_action_events_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationDestination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationDestination) ProtoMessage() {}

func (x *NotificationDestination) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_action_events_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationDestination.ProtoReflect.Descriptor instead.
func (*NotificationDestination) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_action_events_proto_rawDescGZIP(), []int{6}
}

func (x *NotificationDestination) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NotificationDestination) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *NotificationDestination) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *NotificationDestination) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

func (x *NotificationDestination) GetMaxRetries() int32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

var File_pheromone_v1_action_events_proto protoreflect.FileDescriptor

const file_pheromone_v1_action_events_proto_rawDesc = "" +
	"\n" +
	" pheromone/v1/action_events.proto\x12\fpheromone.v1\"\xef\x02\n" +
	"\vActionEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\atwin_id\x18\x02 \x01(\tR\x06twinId\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x03 \x01(\tR\tskillName\x12\x1f\n" +
	"\vaction_type\x18\x04 \x01(\tR\n" +
	"actionType\x12\x18\n" +
	"\aoutcome\x18\x05 \x01(\tR\aoutcome\x12\x16\n" +
	"\x06detail\x18\x06 \x01(\tR\x06detail\x12%\n" +
	"\x0etimestamp_unix\x18\a \x01(\x03R\rtimestampUnix\x12\x19\n" +
	"\btrace_id\x18\b \x01(\tR\atraceId\x12=\n" +
	"\x06labels\x18\t \x03(\v2%.pheromone.v1.ActionEvent.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x0eActionEventAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\x12'\n" +
	"\x0fhooks_triggered\x18\x02 \x01(\x05R\x0ehooksTriggered\"\xad\x02\n" +
	"\x14PackageDeliveryEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\atwin_id\x18\x02 \x01(\tR\x06twinId\x12!\n" +
	"\fpackage_name\x18\x03 \x01(\tR\vpackageName\x12'\n" +
	"\x0fpackage_version\x18\x04 \x01(\tR\x0epackageVersion\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x18\n" +
	"\aoutcome\x18\x06 \x01(\tR\aoutcome\x12!\n" +
	"\ferror_detail\x18\a \x01(\tR\verrorDetail\x12%\n" +
	"\x0etimestamp_unix\x18\b \x01(\x03R\rtimestampUnix\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\".\n" +
	"\x10DeliveryEventAck\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived\".\n" +
	"\x11HookConfigRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\x9f\x02\n" +
	"\n" +
	"HookConfig\x12\x17\n" +
	"\ahook_id\x18\x01 \x01(\tR\x06hookId\x12$\n" +
	"\x0escope_agent_id\x18\x02 \x01(\tR\fscopeAgentId\x12\"\n" +
	"\rscope_twin_id\x18\x03 \x01(\tR\vscopeTwinId\x12\x1f\n" +
	"\vscope_skill\x18\x04 \x01(\tR\n" +
	"scopeSkill\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12%\n" +
	"\x0eoutcome_filter\x18\x06 \x01(\tR\routcomeFilter\x12G\n" +
	"\vdestination\x18\a \x01(\v2%.pheromone.v1.NotificationDestinationR\vdestination\"\x93\x02\n" +
	"\x17NotificationDestination\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12L\n" +
	"\aheaders\x18\x03 \x03(\v22.pheromone.v1.NotificationDestination.HeadersEntryR\aheaders\x12'\n" +
	"\x0ftimeout_seconds\x18\x04 \x01(\x05R\x0etimeoutSeconds\x12\x1f\n" +
	"\vmax_retries\x18\x05 \x01(\x05R\n" +
	"maxRetries\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x8e\x02\n" +
	"\x12ActionEventService\x12L\n" +
	"\x11ReportActionEvent\x12\x19.pheromone.v1.ActionEvent\x1a\x1c.pheromone.v1.ActionEventAck\x12Y\n" +
	"\x13ReportDeliveryEvent\x12\".pheromone.v1.PackageDeliveryEvent\x1a\x1e.pheromone.v1.DeliveryEventAck\x12O\n" +
	"\x10StreamHookConfig\x12\x1f.pheromone.v1.HookConfigRequest\x1a\x18.pheromone.v1.HookConfig0\x01BGZEgithub.com/abuxton/pheromone/internal/proto/pheromone/v1;pheromone_v1b\x06proto3"

var (
	file_pheromone_v1_action_events_proto_rawDescOnce sync.Once
	file_pheromone_v1_action_events_proto_rawDescData []byte
)

func file_pheromone_v1_action_events_proto_rawDescGZIP() []byte {
	file_pheromone_v1_action_events_proto_rawDescOnce.Do(func() {
		file_pheromone_v1_action_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pheromone_v1_action_events_proto_rawDesc), len(file_pheromone_v1_action_events_proto_rawDesc)))
	})
	return file_pheromone_v1_action_events_proto_rawDescData
}

var file_pheromone_v1_action_events_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_pheromone_v1_action_events_proto_goTypes = []any{
	(*ActionEvent)(nil),             // 0: pheromone.v1.ActionEvent
	(*ActionEventAck)(nil),          // 1: pheromone.v1.ActionEventAck
	(*PackageDeliveryEvent)(nil),    // 2: pheromone.v1.PackageDeliveryEvent
	(*DeliveryEventAck)(nil),        // 3: pheromone.v1.DeliveryEventAck
	(*HookConfigRequest)(nil),       // 4: pheromone.v1.HookConfigRequest
	(*HookConfig)(nil),              // 5: pheromone.v1.HookConfig
	(*NotificationDestination)(nil), // 6: pheromone.v1.NotificationDestination
	nil,                             // 7: pheromone.v1.ActionEvent.LabelsEntry
	nil,                             // 8: pheromone.v1.NotificationDestination.HeadersEntry
}
var file_pheromone_v1_action_events_proto_depIdxs = []int32{
	7, // 0: pheromone.v1.ActionEvent.labels:type_name -> pheromone.v1.ActionEvent.LabelsEntry
	6, // 1: pheromone.v1.HookConfig.destination:type_name -> pheromone.v1.NotificationDestination
	8, // 2: pheromone.v1.NotificationDestination.headers:type_name -> pheromone.v1.NotificationDestination.HeadersEntry
	0, // 3: pheromone.v1.ActionEventService.ReportActionEvent:input_type -> pheromone.v1.ActionEvent
	2, // 4: pheromone.v1.ActionEventService.ReportDeliveryEvent:input_type -> pheromone.v1.PackageDeliveryEvent
	4, // 5: pheromone.v1.ActionEventService.StreamHookConfig:input_type -> pheromone.v1.HookConfigRequest
	1, // 6: pheromone.v1.ActionEventService.ReportActionEvent:output_type -> pheromone.v1.ActionEventAck
	3, // 7: pheromone.v1.ActionEventService.ReportDeliveryEvent:output_type -> pheromone.v1.DeliveryEventAck
	5, // 8: pheromone.v1.ActionEventService.StreamHookConfig:output_type -> pheromone.v1.HookConfig
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pheromone_v1_action_events_proto_init() }
func file_pheromone_v1_action_events_proto_init() {
	if File_pheromone_v1_action_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pheromone_v1_action_events_proto_rawDesc), len(file_pheromone_v1_action_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pheromone_v1_action_events_proto_goTypes,
		DependencyIndexes: file_pheromone_v1_action_events_proto_depIdxs,
		MessageInfos:      file_pheromone_v1_action_events_proto_msgTypes,
	}.Build()
	File_pheromone_v1_action_events_proto = out.File
	file_pheromone_v1_action_events_proto_goTypes = nil
	file_pheromone_v1_action_events_proto_depIdxs = nil
}
