// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pheromone/v1/agent_registry.proto

package pheromone_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentCapabilities advertises the AI reasoning and skill capabilities of an agent (ADR-007).
type AgentCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ai_reasoning_enabled is true for agentic AI agents; false for rule-based/legacy agents.
	AiReasoningEnabled bool `protobuf:"varint,1,opt,name=ai_reasoning_enabled,json=aiReasoningEnabled,proto3" json:"ai_reasoning_enabled,omitempty"`
	// ai_model_id identifies the AI reasoning model in use, e.g. "rule-engine-v1" or "llm-local-mistral".
	AiModelId string `protobuf:"bytes,2,opt,name=ai_model_id,json=aiModelId,proto3" json:"ai_model_id,omitempty"`
	// skills lists the skill names this agent supports, e.g. ["digital-twin", "metrics", "config-enforce"].
	Skills []string `protobuf:"bytes,3,rep,name=skills,proto3" json:"skills,omitempty"`
	// skill_contract_version is the semver version of the skill interface implemented by this agent.
	SkillContractVersion string `protobuf:"bytes,4,opt,name=skill_contract_version,json=skillContractVersion,proto3" json:"skill_contract_version,omitempty"`
	// direct_notify_enabled indicates whether the agent supports direct end-user notification (ADR-011).
	DirectNotifyEnabled bool `protobuf:"varint,5,opt,name=direct_notify_enabled,json=directNotifyEnabled,proto3" json:"direct_notify_enabled,omitempty"`
	// notify_dest_types lists the notification destination types supported, e.g. ["http-webhook", "slack"].
	NotifyDestTypes []string `protobuf:"bytes,6,rep,name=notify_dest_types,json=notifyDestTypes,proto3" json:"notify_dest_types,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentCapabilities) Reset() {
	*x = AgentCapabilities{}
	mi := &file_pheromone_v1_agent_registry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCapabilities) ProtoMessage() {}

func (x *AgentCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_agent_registry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCapabilities.ProtoReflect.Descriptor instead.
func (*AgentCapabilities) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_agent_registry_proto_rawDescGZIP(), []int{0}
}

func (x *AgentCapabilities) GetAiReasoningEnabled() bool {
	if x != nil {
		return x.AiReasoningEnabled
	}
	return false
}

func (x *AgentCapabilities) GetAiModelId() string {
	if x != nil {
		return x.AiModelId
	}
	return ""
}

func (x *AgentCapabilities) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *AgentCapabilities) GetSkillContractVersion() string {
	if x != nil {
		return x.SkillContractVersion
	}
	return ""
}

func (x *AgentCapabilities) GetDirectNotifyEnabled() bool {
	if x != nil {
		return x.DirectNotifyEnabled
	}
	return false
}

func (x *AgentCapabilities) GetNotifyDestTypes() []string {
	if x != nil {
		return x.NotifyDestTypes
	}
	return nil
}

// RegisterRequest is sent by an agent to register with the server.
type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id is the unique identifier for this agent instance.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// agent_type describes the agent implementation, e.g. "native-go", "native-python", "custom-rust".
	AgentType string `protobuf:"bytes,2,opt,name=agent_type,json=agentType,proto3" json:"agent_type,omitempty"`
	// hostname is the FQDN or short hostname of the managed instance.
	Hostname string `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	// twin_ids lists the OS and workload twin IDs managed by this agent.
	TwinIds []string `protobuf:"bytes,4,rep,name=twin_ids,json=twinIds,proto3" json:"twin_ids,omitempty"`
	// metadata contains arbitrary key-value pairs, e.g. {"version": "v1.0.0"}.
	Metadata map[string]string `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// capabilities declares the agent's AI reasoning and skill capabilities (ADR-007).
	Capabilities  *AgentCapabilities `protobuf:"bytes,6,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_pheromone_v1_agent_registry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_agent_registry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_agent_registry_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *RegisterRequest) GetAgentType() string {
	if x != nil {
		return x.AgentType
	}
	return ""
}

func (x *RegisterRequest) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *RegisterRequest) GetTwinIds() []string {
	if x != nil {
		return x.TwinIds
	}
	return nil
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterRequest) GetCapabilities() *AgentCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// RegisterResponse is returned by the server after a successful agent registration.
type RegisterResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_id is the unique identifier of the responding server instance.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// accepted indicates whether the server accepted the registration.
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// config_version is the version of the desired configuration the server currently holds for this agent.
	ConfigVersion string `protobuf:"bytes,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_pheromone_v1_agent_registry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_agent_registry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_agent_registry_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *RegisterResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterResponse) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

// HeartbeatRequest is sent periodically by an agent to signal liveness.
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id identifies the sending agent.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// timestamp_unix_ms is the agent-local time in milliseconds since the Unix epoch.
	TimestampUnixMs int64 `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_pheromone_v1_agent_registry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_agent_registry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_agent_registry_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// HeartbeatResponse is returned by the server to acknowledge receipt of a heartbeat.
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_id is the unique identifier of the responding server instance.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// acknowledged indicates whether the server recognised this agent.
	Acknowledged  bool `protobuf:"varint,2,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_pheromone_v1_agent_registry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_agent_registry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_agent_registry_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

var File_pheromone_v1_agent_registry_proto protoreflect.FileDescriptor

const file_pheromone_v1_agent_registry_proto_rawDesc = "" +
	"\n" +
	"!pheromone/v1/agent_registry.proto\x12\fpheromone.v1\"\x93\x02\n" +
	"\x11AgentCapabilities\x120\n" +
	"\x14ai_reasoning_enabled\x18\x01 \x01(\bR\x12aiReasoningEnabled\x12\x1e\n" +
	"\vai_model_id\x18\x02 \x01(\tR\taiModelId\x12\x16\n" +
	"\x06skills\x18\x03 \x03(\tR\x06skills\x124\n" +
	"\x16skill_contract_version\x18\x04 \x01(\tR\x14skillContractVersion\x122\n" +
	"\x15direct_notify_enabled\x18\x05 \x01(\bR\x13directNotifyEnabled\x12*\n" +
	"\x11notify_dest_types\x18\x06 \x03(\tR\x0fnotifyDestTypes\"\xcd\x02\n" +
	"\x0fRegisterRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_type\x18\x02 \x01(\tR\tagentType\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x19\n" +
	"\btwin_ids\x18\x04 \x03(\tR\atwinIds\x12G\n" +
	"\bmetadata\x18\x05 \x03(\v2+.pheromone.v1.RegisterRequest.MetadataEntryR\bmetadata\x12C\n" +
	"\fcapabilities\x18\x06 \x01(\v2\x1f.pheromone.v1.AgentCapabilitiesR\fcapabilities\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x10RegisterResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\tR\rconfigVersion\"Y\n" +
	"\x10HeartbeatRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\"T\n" +
	"\x11HeartbeatResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\"\n" +
	"\facknowledged\x18\x02 \x01(\bR\facknowledged2\xa8\x01\n" +
	"\rAgentRegistry\x12I\n" +
	"\bRegister\x12\x1d.pheromone.v1.RegisterRequest\x1a\x1e.pheromone.v1.RegisterResponse\x12L\n" +
	"\tHeartbeat\x12\x1e.pheromone.v1.HeartbeatRequest\x1a\x1f.pheromone.v1.HeartbeatResponseBGZEgithub.com/abuxton/pheromone/internal/proto/pheromone/v1;pheromone_v1b\x06proto3"

var (
	file_pheromone_v1_agent_registry_proto_rawDescOnce sync.Once
	file_pheromone_v1_agent_registry_proto_rawDescData []byte
)

func file_pheromone_v1_agent_registry_proto_rawDescGZIP() []byte {
	file_pheromone_v1_agent_registry_proto_rawDescOnce.Do(func() {
		file_pheromone_v1_agent_registry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pheromone_v1_agent_registry_proto_rawDesc), len(file_pheromone_v1_agent_registry_proto_rawDesc)))
	})
	return file_pheromone_v1_agent_registry_proto_rawDescData
}

var file_pheromone_v1_agent_registry_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pheromone_v1_agent_registry_proto_goTypes = []any{
	(*AgentCapabilities)(nil), // 0: pheromone.v1.AgentCapabilities
	(*RegisterRequest)(nil),   // 1: pheromone.v1.RegisterRequest
	(*RegisterResponse)(nil),  // 2: pheromone.v1.RegisterResponse
	(*HeartbeatRequest)(nil),  // 3: pheromone.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 4: pheromone.v1.HeartbeatResponse
	nil,                       // 5: pheromone.v1.RegisterRequest.MetadataEntry
}
var file_pheromone_v1_agent_registry_proto_depIdxs = []int32{
	5, // 0: pheromone.v1.RegisterRequest.metadata:type_name -> pheromone.v1.RegisterRequest.MetadataEntry
	0, // 1: pheromone.v1.RegisterRequest.capabilities:type_name -> pheromone.v1.AgentCapabilities
	1, // 2: pheromone.v1.AgentRegistry.Register:input_type -> pheromone.v1.RegisterRequest
	3, // 3: pheromone.v1.AgentRegistry.Heartbeat:input_type -> pheromone.v1.HeartbeatRequest
	2, // 4: pheromone.v1.AgentRegistry.Register:output_type -> pheromone.v1.RegisterResponse
	4, // 5: pheromone.v1.AgentRegistry.Heartbeat:output_type -> pheromone.v1.HeartbeatResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pheromone_v1_agent_registry_proto_init() }
func file_pheromone_v1_agent_registry_proto_init() {
	if File_pheromone_v1_agent_registry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pheromone_v1_agent_registry_proto_rawDesc), len(file_pheromone_v1_agent_registry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pheromone_v1_agent_registry_proto_goTypes,
		DependencyIndexes: file_pheromone_v1_agent_registry_proto_depIdxs,
		MessageInfos:      file_pheromone_v1_agent_registry_proto_msgTypes,
	}.Build()
	File_pheromone_v1_agent_registry_proto = out.File
	file_pheromone_v1_agent_registry_proto_goTypes = nil
	file_pheromone_v1_agent_registry_proto_depIdxs = nil
}
