// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: pheromone/v1/telemetry.proto

package pheromone_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TelemetryStream_StreamMetrics_FullMethodName = "/pheromone.v1.TelemetryStream/StreamMetrics"
)

// TelemetryStreamClient is the client API for TelemetryStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TelemetryStream provides bidirectional streaming of metrics, logs, and AI decision
// traces from agent to server (ADR-003, ADR-007).
type TelemetryStreamClient interface {
	// StreamMetrics is a bidirectional stream: the agent continuously emits metric/log/trace
	// batches; the server acknowledges receipt and applies backpressure when needed.
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MetricsRequest, MetricsResponse], error)
}

type telemetryStreamClient struct {
	cc grpc.ClientConnInterface
}

func NewTelemetryStreamClient(cc grpc.ClientConnInterface) TelemetryStreamClient {
	return &telemetryStreamClient{cc}
}

func (c *telemetryStreamClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MetricsRequest, MetricsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TelemetryStream_ServiceDesc.Streams[0], TelemetryStream_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricsRequest, MetricsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryStream_StreamMetricsClient = grpc.BidiStreamingClient[MetricsRequest, MetricsResponse]

// TelemetryStreamServer is the server API for TelemetryStream service.
// All implementations should embed UnimplementedTelemetryStreamServer
// for forward compatibility.
//
// TelemetryStream provides bidirectional streaming of metrics, logs, and AI decision
// traces from agent to server (ADR-003, ADR-007).
type TelemetryStreamServer interface {
	// StreamMetrics is a bidirectional stream: the agent continuously emits metric/log/trace
	// batches; the server acknowledges receipt and applies backpressure when needed.
	StreamMetrics(grpc.BidiStreamingServer[MetricsRequest, MetricsResponse]) error
}

// UnimplementedTelemetryStreamServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTelemetryStreamServer struct{}

func (UnimplementedTelemetryStreamServer) StreamMetrics(grpc.BidiStreamingServer[MetricsRequest, MetricsResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedTelemetryStreamServer) testEmbeddedByValue() {}

// UnsafeTelemetryStreamServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TelemetryStreamServer will
// result in compilation errors.
type UnsafeTelemetryStreamServer interface {
	mustEmbedUnimplementedTelemetryStreamServer()
}

func RegisterTelemetryStreamServer(s grpc.ServiceRegistrar, srv TelemetryStreamServer) {
	// If the following call panics, it indicates UnimplementedTelemetryStreamServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TelemetryStream_ServiceDesc, srv)
}

func _TelemetryStream_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TelemetryStreamServer).StreamMetrics(&grpc.GenericServerStream[MetricsRequest, MetricsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TelemetryStream_StreamMetricsServer = grpc.BidiStreamingServer[MetricsRequest, MetricsResponse]

// TelemetryStream_ServiceDesc is the grpc.ServiceDesc for TelemetryStream service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TelemetryStream_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pheromone.v1.TelemetryStream",
	HandlerType: (*TelemetryStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _TelemetryStream_StreamMetrics_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pheromone/v1/telemetry.proto",
}
