// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pheromone/v1/telemetry.proto

package pheromone_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Metric represents a single metric observation in OpenMetrics format.
type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the metric name, e.g. "cpu_usage_percent".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// value is the numeric measurement.
	Value float64 `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	// labels contains key-value pairs used to identify the metric source.
	Labels map[string]string `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// timestamp_unix_ms is the observation time in milliseconds since the Unix epoch.
	TimestampUnixMs int64 `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_pheromone_v1_telemetry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_telemetry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_telemetry_proto_rawDescGZIP(), []int{0}
}

func (x *Metric) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Metric) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Metric) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// LogEntry represents a single structured log record.
type LogEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// level is the log severity, e.g. "info", "warn", "error".
	Level string `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	// message is the human-readable log text.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// fields contains structured key-value context for the log entry.
	Fields map[string]string `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// timestamp_unix_ms is the time the log entry was emitted, in milliseconds since the Unix epoch.
	TimestampUnixMs int64 `protobuf:"varint,4,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_pheromone_v1_telemetry_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_telemetry_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_telemetry_proto_rawDescGZIP(), []int{1}
}

func (x *LogEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEntry) GetFields() map[string]string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *LogEntry) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

// AIDecisionTrace captures one iteration of the agent's AI reasoning loop (ADR-007).
type AIDecisionTrace struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// trace_id correlates this trace with the corresponding TelemetryStream trace_id.
	TraceId string `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// timestamp_unix_ms is the time the reasoning iteration completed, in milliseconds.
	TimestampUnixMs int64 `protobuf:"varint,2,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	// observations_count is the number of observations (metrics, logs, twin reads) ingested.
	ObservationsCount int32 `protobuf:"varint,3,opt,name=observations_count,json=observationsCount,proto3" json:"observations_count,omitempty"`
	// drift_detected is true when the reasoner identified a gap between desired and actual state.
	DriftDetected bool `protobuf:"varint,4,opt,name=drift_detected,json=driftDetected,proto3" json:"drift_detected,omitempty"`
	// actions_planned is the number of actions generated by the reasoning step.
	ActionsPlanned int32 `protobuf:"varint,5,opt,name=actions_planned,json=actionsPlanned,proto3" json:"actions_planned,omitempty"`
	// actions_executed is the number of actions successfully executed.
	ActionsExecuted int32 `protobuf:"varint,6,opt,name=actions_executed,json=actionsExecuted,proto3" json:"actions_executed,omitempty"`
	// actions_proposed is the number of actions submitted to the server for approval via ProposeAction.
	ActionsProposed int32 `protobuf:"varint,7,opt,name=actions_proposed,json=actionsProposed,proto3" json:"actions_proposed,omitempty"`
	// twin_updates lists the twin IDs whose state was updated during this reasoning iteration.
	TwinUpdates   []string `protobuf:"bytes,8,rep,name=twin_updates,json=twinUpdates,proto3" json:"twin_updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AIDecisionTrace) Reset() {
	*x = AIDecisionTrace{}
	mi := &file_pheromone_v1_telemetry_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AIDecisionTrace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AIDecisionTrace) ProtoMessage() {}

func (x *AIDecisionTrace) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_telemetry_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AIDecisionTrace.ProtoReflect.Descriptor instead.
func (*AIDecisionTrace) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_telemetry_proto_rawDescGZIP(), []int{2}
}

func (x *AIDecisionTrace) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AIDecisionTrace) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

func (x *AIDecisionTrace) GetObservationsCount() int32 {
	if x != nil {
		return x.ObservationsCount
	}
	return 0
}

func (x *AIDecisionTrace) GetDriftDetected() bool {
	if x != nil {
		return x.DriftDetected
	}
	return false
}

func (x *AIDecisionTrace) GetActionsPlanned() int32 {
	if x != nil {
		return x.ActionsPlanned
	}
	return 0
}

func (x *AIDecisionTrace) GetActionsExecuted() int32 {
	if x != nil {
		return x.ActionsExecuted
	}
	return 0
}

func (x *AIDecisionTrace) GetActionsProposed() int32 {
	if x != nil {
		return x.ActionsProposed
	}
	return 0
}

func (x *AIDecisionTrace) GetTwinUpdates() []string {
	if x != nil {
		return x.TwinUpdates
	}
	return nil
}

// MetricsRequest is streamed by the agent to deliver metric/log/trace batches.
type MetricsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id identifies the sending agent.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// trace_id is the distributed trace identifier for this batch.
	TraceId string `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// metrics contains the metric observations to be delivered.
	Metrics []*Metric `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	// logs contains the structured log entries to be delivered.
	Logs []*LogEntry `protobuf:"bytes,4,rep,name=logs,proto3" json:"logs,omitempty"`
	// ai_traces contains AI reasoning loop decision traces (ADR-007).
	AiTraces      []*AIDecisionTrace `protobuf:"bytes,5,rep,name=ai_traces,json=aiTraces,proto3" json:"ai_traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsRequest) Reset() {
	*x = MetricsRequest{}
	mi := &file_pheromone_v1_telemetry_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsRequest) ProtoMessage() {}

func (x *MetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_telemetry_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsRequest.ProtoReflect.Descriptor instead.
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_telemetry_proto_rawDescGZIP(), []int{3}
}

func (x *MetricsRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricsRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *MetricsRequest) GetMetrics() []*Metric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricsRequest) GetLogs() []*LogEntry {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *MetricsRequest) GetAiTraces() []*AIDecisionTrace {
	if x != nil {
		return x.AiTraces
	}
	return nil
}

// MetricsResponse is streamed by the server to acknowledge receipt and signal backpressure.
type MetricsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_id is the unique identifier of the responding server instance.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// acked_count is the total number of metric observations received in the last batch.
	AckedCount int32 `protobuf:"varint,2,opt,name=acked_count,json=ackedCount,proto3" json:"acked_count,omitempty"`
	// ready_for_next signals whether the server is ready to receive the next batch.
	// When false, the agent should pause before sending additional data (backpressure).
	ReadyForNext  bool `protobuf:"varint,3,opt,name=ready_for_next,json=readyForNext,proto3" json:"ready_for_next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricsResponse) Reset() {
	*x = MetricsResponse{}
	mi := &file_pheromone_v1_telemetry_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsResponse) ProtoMessage() {}

func (x *MetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_telemetry_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsResponse.ProtoReflect.Descriptor instead.
func (*MetricsResponse) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_telemetry_proto_rawDescGZIP(), []int{4}
}

func (x *MetricsResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *MetricsResponse) GetAckedCount() int32 {
	if x != nil {
		return x.AckedCount
	}
	return 0
}

func (x *MetricsResponse) GetReadyForNext() bool {
	if x != nil {
		return x.ReadyForNext
	}
	return false
}

var File_pheromone_v1_telemetry_proto protoreflect.FileDescriptor

const file_pheromone_v1_telemetry_proto_rawDesc = "" +
	"\n" +
	"\x1cpheromone/v1/telemetry.proto\x12\fpheromone.v1\"\xd3\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x128\n" +
	"\x06labels\x18\x03 \x03(\v2 .pheromone.v1.Metric.LabelsEntryR\x06labels\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdd\x01\n" +
	"\bLogEntry\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12:\n" +
	"\x06fields\x18\x03 \x03(\v2\".pheromone.v1.LogEntry.FieldsEntryR\x06fields\x12*\n" +
	"\x11timestamp_unix_ms\x18\x04 \x01(\x03R\x0ftimestampUnixMs\x1a9\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x02\n" +
	"\x0fAIDecisionTrace\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12*\n" +
	"\x11timestamp_unix_ms\x18\x02 \x01(\x03R\x0ftimestampUnixMs\x12-\n" +
	"\x12observations_count\x18\x03 \x01(\x05R\x11observationsCount\x12%\n" +
	"\x0edrift_detected\x18\x04 \x01(\bR\rdriftDetected\x12'\n" +
	"\x0factions_planned\x18\x05 \x01(\x05R\x0eactionsPlanned\x12)\n" +
	"\x10actions_executed\x18\x06 \x01(\x05R\x0factionsExecuted\x12)\n" +
	"\x10actions_proposed\x18\a \x01(\x05R\x0factionsProposed\x12!\n" +
	"\ftwin_updates\x18\b \x03(\tR\vtwinUpdates\"\xde\x01\n" +
	"\x0eMetricsRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12.\n" +
	"\ametrics\x18\x03 \x03(\v2\x14.pheromone.v1.MetricR\ametrics\x12*\n" +
	"\x04logs\x18\x04 \x03(\v2\x16.pheromone.v1.LogEntryR\x04logs\x12:\n" +
	"\tai_traces\x18\x05 \x03(\v2\x1d.pheromone.v1.AIDecisionTraceR\baiTraces\"u\n" +
	"\x0fMetricsResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1f\n" +
	"\vacked_count\x18\x02 \x01(\x05R\n" +
	"ackedCount\x12$\n" +
	"\x0eready_for_next\x18\x03 \x01(\bR\freadyForNext2c\n" +
	"\x0fTelemetryStream\x12P\n" +
	"\rStreamMetrics\x12\x1c.pheromone.v1.MetricsRequest\x1a\x1d.pheromone.v1.MetricsResponse(\x010\x01BGZEgithub.com/abuxton/pheromone/internal/proto/pheromone/v1;pheromone_v1b\x06proto3"

var (
	file_pheromone_v1_telemetry_proto_rawDescOnce sync.Once
	file_pheromone_v1_telemetry_proto_rawDescData []byte
)

func file_pheromone_v1_telemetry_proto_rawDescGZIP() []byte {
	file_pheromone_v1_telemetry_proto_rawDescOnce.Do(func() {
		file_pheromone_v1_telemetry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pheromone_v1_telemetry_proto_rawDesc), len(file_pheromone_v1_telemetry_proto_rawDesc)))
	})
	return file_pheromone_v1_telemetry_proto_rawDescData
}

var file_pheromone_v1_telemetry_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pheromone_v1_telemetry_proto_goTypes = []any{
	(*Metric)(nil),          // 0: pheromone.v1.Metric
	(*LogEntry)(nil),        // 1: pheromone.v1.LogEntry
	(*AIDecisionTrace)(nil), // 2: pheromone.v1.AIDecisionTrace
	(*MetricsRequest)(nil),  // 3: pheromone.v1.MetricsRequest
	(*MetricsResponse)(nil), // 4: pheromone.v1.MetricsResponse
	nil,                     // 5: pheromone.v1.Metric.LabelsEntry
	nil,                     // 6: pheromone.v1.LogEntry.FieldsEntry
}
var file_pheromone_v1_telemetry_proto_depIdxs = []int32{
	5, // 0: pheromone.v1.Metric.labels:type_name -> pheromone.v1.Metric.LabelsEntry
	6, // 1: pheromone.v1.LogEntry.fields:type_name -> pheromone.v1.LogEntry.FieldsEntry
	0, // 2: pheromone.v1.MetricsRequest.metrics:type_name -> pheromone.v1.Metric
	1, // 3: pheromone.v1.MetricsRequest.logs:type_name -> pheromone.v1.LogEntry
	2, // 4: pheromone.v1.MetricsRequest.ai_traces:type_name -> pheromone.v1.AIDecisionTrace
	3, // 5: pheromone.v1.TelemetryStream.StreamMetrics:input_type -> pheromone.v1.MetricsRequest
	4, // 6: pheromone.v1.TelemetryStream.StreamMetrics:output_type -> pheromone.v1.MetricsResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_pheromone_v1_telemetry_proto_init() }
func file_pheromone_v1_telemetry_proto_init() {
	if File_pheromone_v1_telemetry_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pheromone_v1_telemetry_proto_rawDesc), len(file_pheromone_v1_telemetry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pheromone_v1_telemetry_proto_goTypes,
		DependencyIndexes: file_pheromone_v1_telemetry_proto_depIdxs,
		MessageInfos:      file_pheromone_v1_telemetry_proto_msgTypes,
	}.Build()
	File_pheromone_v1_telemetry_proto = out.File
	file_pheromone_v1_telemetry_proto_goTypes = nil
	file_pheromone_v1_telemetry_proto_depIdxs = nil
}
