// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: pheromone/v1/twin_control.proto

package pheromone_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Twin represents a digital twin state snapshot carried over the wire.
type Twin struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// twin_id is the unique identifier of the twin.
	TwinId string `protobuf:"bytes,1,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	// twin_type is "os-level" or "workload".
	TwinType string `protobuf:"bytes,2,opt,name=twin_type,json=twinType,proto3" json:"twin_type,omitempty"`
	// state_json is a JSON-encoded snapshot of the twin's current state.
	StateJson []byte `protobuf:"bytes,3,opt,name=state_json,json=stateJson,proto3" json:"state_json,omitempty"`
	// config_version is the version of the twin state being reported.
	ConfigVersion string `protobuf:"bytes,4,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Twin) Reset() {
	*x = Twin{}
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Twin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Twin) ProtoMessage() {}

func (x *Twin) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Twin.ProtoReflect.Descriptor instead.
func (*Twin) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_twin_control_proto_rawDescGZIP(), []int{0}
}

func (x *Twin) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *Twin) GetTwinType() string {
	if x != nil {
		return x.TwinType
	}
	return ""
}

func (x *Twin) GetStateJson() []byte {
	if x != nil {
		return x.StateJson
	}
	return nil
}

func (x *Twin) GetConfigVersion() string {
	if x != nil {
		return x.ConfigVersion
	}
	return ""
}

// EnforcementStatus reports whether an agent is compliant with the desired twin configuration.
type EnforcementStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// twin_id identifies the twin this status applies to.
	TwinId string `protobuf:"bytes,1,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	// compliant is true when actual state matches desired state.
	Compliant bool `protobuf:"varint,2,opt,name=compliant,proto3" json:"compliant,omitempty"`
	// drift_summary is a human-readable description of any detected drift.
	DriftSummary  string `protobuf:"bytes,3,opt,name=drift_summary,json=driftSummary,proto3" json:"drift_summary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnforcementStatus) Reset() {
	*x = EnforcementStatus{}
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnforcementStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnforcementStatus) ProtoMessage() {}

func (x *EnforcementStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnforcementStatus.ProtoReflect.Descriptor instead.
func (*EnforcementStatus) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_twin_control_proto_rawDescGZIP(), []int{1}
}

func (x *EnforcementStatus) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *EnforcementStatus) GetCompliant() bool {
	if x != nil {
		return x.Compliant
	}
	return false
}

func (x *EnforcementStatus) GetDriftSummary() string {
	if x != nil {
		return x.DriftSummary
	}
	return ""
}

// ConfigAction is a server-issued instruction carried in a TwinSyncResponse.
type ConfigAction struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// action_id is a unique identifier for this action, used for idempotency.
	ActionId string `protobuf:"bytes,1,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	// action_type describes the operation, e.g. "apply-config", "collect-metrics", "rollback".
	ActionType string `protobuf:"bytes,2,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	// twin_id is the target twin for this action.
	TwinId string `protobuf:"bytes,3,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	// payload_json is JSON-encoded parameters for the action.
	PayloadJson   []byte `protobuf:"bytes,4,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigAction) Reset() {
	*x = ConfigAction{}
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigAction) ProtoMessage() {}

func (x *ConfigAction) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigAction.ProtoReflect.Descriptor instead.
func (*ConfigAction) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_twin_control_proto_rawDescGZIP(), []int{2}
}

func (x *ConfigAction) GetActionId() string {
	if x != nil {
		return x.ActionId
	}
	return ""
}

func (x *ConfigAction) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *ConfigAction) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *ConfigAction) GetPayloadJson() []byte {
	if x != nil {
		return x.PayloadJson
	}
	return nil
}

// TwinSyncRequest is streamed by the agent to report actual state and enforcement status.
type TwinSyncRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id identifies the sending agent.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// actual_state contains the agent's view of all managed twin states.
	ActualState []*Twin `protobuf:"bytes,2,rep,name=actual_state,json=actualState,proto3" json:"actual_state,omitempty"`
	// enforcement_status reports compliance with the currently applied desired config.
	EnforcementStatus []*EnforcementStatus `protobuf:"bytes,3,rep,name=enforcement_status,json=enforcementStatus,proto3" json:"enforcement_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TwinSyncRequest) Reset() {
	*x = TwinSyncRequest{}
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwinSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwinSyncRequest) ProtoMessage() {}

func (x *TwinSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwinSyncRequest.ProtoReflect.Descriptor instead.
func (*TwinSyncRequest) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_twin_control_proto_rawDescGZIP(), []int{3}
}

func (x *TwinSyncRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TwinSyncRequest) GetActualState() []*Twin {
	if x != nil {
		return x.ActualState
	}
	return nil
}

func (x *TwinSyncRequest) GetEnforcementStatus() []*EnforcementStatus {
	if x != nil {
		return x.EnforcementStatus
	}
	return nil
}

// TwinSyncResponse is streamed by the server to push desired configuration and actions.
type TwinSyncResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_id is the unique identifier of the responding server instance.
	ServerId string `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	// actions lists the operations the agent should execute.
	Actions []*ConfigAction `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
	// desired_config_version is the version of the desired state being pushed.
	DesiredConfigVersion string `protobuf:"bytes,3,opt,name=desired_config_version,json=desiredConfigVersion,proto3" json:"desired_config_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TwinSyncResponse) Reset() {
	*x = TwinSyncResponse{}
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TwinSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TwinSyncResponse) ProtoMessage() {}

func (x *TwinSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TwinSyncResponse.ProtoReflect.Descriptor instead.
func (*TwinSyncResponse) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_twin_control_proto_rawDescGZIP(), []int{4}
}

func (x *TwinSyncResponse) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *TwinSyncResponse) GetActions() []*ConfigAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *TwinSyncResponse) GetDesiredConfigVersion() string {
	if x != nil {
		return x.DesiredConfigVersion
	}
	return ""
}

// ActionProposal is sent by an AI agent when it wants to execute an action that
// requires server-side (or operator) approval (ADR-007).
type ActionProposal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent_id identifies the proposing agent.
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// twin_id is the target twin for the proposed action.
	TwinId string `protobuf:"bytes,2,opt,name=twin_id,json=twinId,proto3" json:"twin_id,omitempty"`
	// skill_name names the skill that would execute the action, e.g. "config-enforce".
	SkillName string `protobuf:"bytes,3,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	// rationale is a natural-language summary of the AI reasoning behind this proposal.
	Rationale string `protobuf:"bytes,4,opt,name=rationale,proto3" json:"rationale,omitempty"`
	// action_payload is the serialised action parameters.
	ActionPayload []byte `protobuf:"bytes,5,opt,name=action_payload,json=actionPayload,proto3" json:"action_payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionProposal) Reset() {
	*x = ActionProposal{}
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionProposal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionProposal) ProtoMessage() {}

func (x *ActionProposal) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionProposal.ProtoReflect.Descriptor instead.
func (*ActionProposal) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_twin_control_proto_rawDescGZIP(), []int{5}
}

func (x *ActionProposal) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ActionProposal) GetTwinId() string {
	if x != nil {
		return x.TwinId
	}
	return ""
}

func (x *ActionProposal) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *ActionProposal) GetRationale() string {
	if x != nil {
		return x.Rationale
	}
	return ""
}

func (x *ActionProposal) GetActionPayload() []byte {
	if x != nil {
		return x.ActionPayload
	}
	return nil
}

// ActionDecision is the server's response to an ActionProposal (ADR-007).
type ActionDecision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// approved is true when the server (or operator policy) permits the proposed action.
	Approved bool `protobuf:"varint,1,opt,name=approved,proto3" json:"approved,omitempty"`
	// decision_by identifies who or what approved/rejected the proposal,
	// e.g. "auto-approve", "operator-id-123", "policy-engine".
	DecisionBy string `protobuf:"bytes,2,opt,name=decision_by,json=decisionBy,proto3" json:"decision_by,omitempty"`
	// rejection_reason is populated when approved is false.
	RejectionReason string `protobuf:"bytes,3,opt,name=rejection_reason,json=rejectionReason,proto3" json:"rejection_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ActionDecision) Reset() {
	*x = ActionDecision{}
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionDecision) ProtoMessage() {}

func (x *ActionDecision) ProtoReflect() protoreflect.Message {
	mi := &file_pheromone_v1_twin_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionDecision.ProtoReflect.Descriptor instead.
func (*ActionDecision) Descriptor() ([]byte, []int) {
	return file_pheromone_v1_twin_control_proto_rawDescGZIP(), []int{6}
}

func (x *ActionDecision) GetApproved() bool {
	if x != nil {
		return x.Approved
	}
	return false
}

func (x *ActionDecision) GetDecisionBy() string {
	if x != nil {
		return x.DecisionBy
	}
	return ""
}

func (x *ActionDecision) GetRejectionReason() string {
	if x != nil {
		return x.RejectionReason
	}
	return ""
}

var File_pheromone_v1_twin_control_proto protoreflect.FileDescriptor

const file_pheromone_v1_twin_control_proto_rawDesc = "" +
	"\n" +
	"\x1fpheromone/v1/twin_control.proto\x12\fpheromone.v1\"\x82\x01\n" +
	"\x04Twin\x12\x17\n" +
	"\atwin_id\x18\x01 \x01(\tR\x06twinId\x12\x1b\n" +
	"\ttwin_type\x18\x02 \x01(\tR\btwinType\x12\x1d\n" +
	"\n" +
	"state_json\x18\x03 \x01(\fR\tstateJson\x12%\n" +
	"\x0econfig_version\x18\x04 \x01(\tR\rconfigVersion\"o\n" +
	"\x11EnforcementStatus\x12\x17\n" +
	"\atwin_id\x18\x01 \x01(\tR\x06twinId\x12\x1c\n" +
	"\tcompliant\x18\x02 \x01(\bR\tcompliant\x12#\n" +
	"\rdrift_summary\x18\x03 \x01(\tR\fdriftSummary\"\x88\x01\n" +
	"\fConfigAction\x12\x1b\n" +
	"\taction_id\x18\x01 \x01(\tR\bactionId\x12\x1f\n" +
	"\vaction_type\x18\x02 \x01(\tR\n" +
	"actionType\x12\x17\n" +
	"\atwin_id\x18\x03 \x01(\tR\x06twinId\x12!\n" +
	"\fpayload_json\x18\x04 \x01(\fR\vpayloadJson\"\xb3\x01\n" +
	"\x0fTwinSyncRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x125\n" +
	"\factual_state\x18\x02 \x03(\v2\x12.pheromone.v1.TwinR\vactualState\x12N\n" +
	"\x12enforcement_status\x18\x03 \x03(\v2\x1f.pheromone.v1.EnforcementStatusR\x11enforcementStatus\"\x9b\x01\n" +
	"\x10TwinSyncResponse\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x124\n" +
	"\aactions\x18\x02 \x03(\v2\x1a.pheromone.v1.ConfigActionR\aactions\x124\n" +
	"\x16desired_config_version\x18\x03 \x01(\tR\x14desiredConfigVersion\"\xa8\x01\n" +
	"\x0eActionProposal\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x17\n" +
	"\atwin_id\x18\x02 \x01(\tR\x06twinId\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x03 \x01(\tR\tskillName\x12\x1c\n" +
	"\trationale\x18\x04 \x01(\tR\trationale\x12%\n" +
	"\x0eaction_payload\x18\x05 \x01(\fR\ractionPayload\"x\n" +
	"\x0eActionDecision\x12\x1a\n" +
	"\bapproved\x18\x01 \x01(\bR\bapproved\x12\x1f\n" +
	"\vdecision_by\x18\x02 \x01(\tR\n" +
	"decisionBy\x12)\n" +
	"\x10rejection_reason\x18\x03 \x01(\tR\x0frejectionReason2\xae\x01\n" +
	"\vTwinControl\x12R\n" +
	"\rSyncTwinState\x12\x1d.pheromone.v1.TwinSyncRequest\x1a\x1e.pheromone.v1.TwinSyncResponse(\x010\x01\x12K\n" +
	"\rProposeAction\x12\x1c.pheromone.v1.ActionProposal\x1a\x1c.pheromone.v1.ActionDecisionBGZEgithub.com/abuxton/pheromone/internal/proto/pheromone/v1;pheromone_v1b\x06proto3"

var (
	file_pheromone_v1_twin_control_proto_rawDescOnce sync.Once
	file_pheromone_v1_twin_control_proto_rawDescData []byte
)

func file_pheromone_v1_twin_control_proto_rawDescGZIP() []byte {
	file_pheromone_v1_twin_control_proto_rawDescOnce.Do(func() {
		file_pheromone_v1_twin_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pheromone_v1_twin_control_proto_rawDesc), len(file_pheromone_v1_twin_control_proto_rawDesc)))
	})
	return file_pheromone_v1_twin_control_proto_rawDescData
}

var file_pheromone_v1_twin_control_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pheromone_v1_twin_control_proto_goTypes = []any{
	(*Twin)(nil),              // 0: pheromone.v1.Twin
	(*EnforcementStatus)(nil), // 1: pheromone.v1.EnforcementStatus
	(*ConfigAction)(nil),      // 2: pheromone.v1.ConfigAction
	(*TwinSyncRequest)(nil),   // 3: pheromone.v1.TwinSyncRequest
	(*TwinSyncResponse)(nil),  // 4: pheromone.v1.TwinSyncResponse
	(*ActionProposal)(nil),    // 5: pheromone.v1.ActionProposal
	(*ActionDecision)(nil),    // 6: pheromone.v1.ActionDecision
}
var file_pheromone_v1_twin_control_proto_depIdxs = []int32{
	0, // 0: pheromone.v1.TwinSyncRequest.actual_state:type_name -> pheromone.v1.Twin
	1, // 1: pheromone.v1.TwinSyncRequest.enforcement_status:type_name -> pheromone.v1.EnforcementStatus
	2, // 2: pheromone.v1.TwinSyncResponse.actions:type_name -> pheromone.v1.ConfigAction
	3, // 3: pheromone.v1.TwinControl.SyncTwinState:input_type -> pheromone.v1.TwinSyncRequest
	5, // 4: pheromone.v1.TwinControl.ProposeAction:input_type -> pheromone.v1.ActionProposal
	4, // 5: pheromone.v1.TwinControl.SyncTwinState:output_type -> pheromone.v1.TwinSyncResponse
	6, // 6: pheromone.v1.TwinControl.ProposeAction:output_type -> pheromone.v1.ActionDecision
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pheromone_v1_twin_control_proto_init() }
func file_pheromone_v1_twin_control_proto_init() {
	if File_pheromone_v1_twin_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pheromone_v1_twin_control_proto_rawDesc), len(file_pheromone_v1_twin_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pheromone_v1_twin_control_proto_goTypes,
		DependencyIndexes: file_pheromone_v1_twin_control_proto_depIdxs,
		MessageInfos:      file_pheromone_v1_twin_control_proto_msgTypes,
	}.Build()
	File_pheromone_v1_twin_control_proto = out.File
	file_pheromone_v1_twin_control_proto_goTypes = nil
	file_pheromone_v1_twin_control_proto_depIdxs = nil
}
