// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: pheromone/v1/twin_control.proto

package pheromone_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TwinControl_SyncTwinState_FullMethodName = "/pheromone.v1.TwinControl/SyncTwinState"
	TwinControl_ProposeAction_FullMethodName = "/pheromone.v1.TwinControl/ProposeAction"
)

// TwinControlClient is the client API for TwinControl service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TwinControl provides bidirectional streaming for twin-state synchronisation and
// an RPC for agentic AI action proposals (ADR-007 human-in-the-loop).
type TwinControlClient interface {
	// SyncTwinState is a bidirectional stream: the agent continuously reports actual state
	// and enforcement status; the server pushes desired configuration and actions in return.
	SyncTwinState(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TwinSyncRequest, TwinSyncResponse], error)
	// ProposeAction allows an AI agent to submit an action proposal for server-side
	// approval before execution (ADR-007 human-in-the-loop gate).
	ProposeAction(ctx context.Context, in *ActionProposal, opts ...grpc.CallOption) (*ActionDecision, error)
}

type twinControlClient struct {
	cc grpc.ClientConnInterface
}

func NewTwinControlClient(cc grpc.ClientConnInterface) TwinControlClient {
	return &twinControlClient{cc}
}

func (c *twinControlClient) SyncTwinState(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TwinSyncRequest, TwinSyncResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TwinControl_ServiceDesc.Streams[0], TwinControl_SyncTwinState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TwinSyncRequest, TwinSyncResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TwinControl_SyncTwinStateClient = grpc.BidiStreamingClient[TwinSyncRequest, TwinSyncResponse]

func (c *twinControlClient) ProposeAction(ctx context.Context, in *ActionProposal, opts ...grpc.CallOption) (*ActionDecision, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionDecision)
	err := c.cc.Invoke(ctx, TwinControl_ProposeAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TwinControlServer is the server API for TwinControl service.
// All implementations should embed UnimplementedTwinControlServer
// for forward compatibility.
//
// TwinControl provides bidirectional streaming for twin-state synchronisation and
// an RPC for agentic AI action proposals (ADR-007 human-in-the-loop).
type TwinControlServer interface {
	// SyncTwinState is a bidirectional stream: the agent continuously reports actual state
	// and enforcement status; the server pushes desired configuration and actions in return.
	SyncTwinState(grpc.BidiStreamingServer[TwinSyncRequest, TwinSyncResponse]) error
	// ProposeAction allows an AI agent to submit an action proposal for server-side
	// approval before execution (ADR-007 human-in-the-loop gate).
	ProposeAction(context.Context, *ActionProposal) (*ActionDecision, error)
}

// UnimplementedTwinControlServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTwinControlServer struct{}

func (UnimplementedTwinControlServer) SyncTwinState(grpc.BidiStreamingServer[TwinSyncRequest, TwinSyncResponse]) error {
	return status.Error(codes.Unimplemented, "method SyncTwinState not implemented")
}
func (UnimplementedTwinControlServer) ProposeAction(context.Context, *ActionProposal) (*ActionDecision, error) {
	return nil, status.Error(codes.Unimplemented, "method ProposeAction not implemented")
}
func (UnimplementedTwinControlServer) testEmbeddedByValue() {}

// UnsafeTwinControlServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TwinControlServer will
// result in compilation errors.
type UnsafeTwinControlServer interface {
	mustEmbedUnimplementedTwinControlServer()
}

func RegisterTwinControlServer(s grpc.ServiceRegistrar, srv TwinControlServer) {
	// If the following call panics, it indicates UnimplementedTwinControlServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TwinControl_ServiceDesc, srv)
}

func _TwinControl_SyncTwinState_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TwinControlServer).SyncTwinState(&grpc.GenericServerStream[TwinSyncRequest, TwinSyncResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TwinControl_SyncTwinStateServer = grpc.BidiStreamingServer[TwinSyncRequest, TwinSyncResponse]

func _TwinControl_ProposeAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActionProposal)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TwinControlServer).ProposeAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TwinControl_ProposeAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TwinControlServer).ProposeAction(ctx, req.(*ActionProposal))
	}
	return interceptor(ctx, in, info, handler)
}

// TwinControl_ServiceDesc is the grpc.ServiceDesc for TwinControl service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TwinControl_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pheromone.v1.TwinControl",
	HandlerType: (*TwinControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProposeAction",
			Handler:    _TwinControl_ProposeAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SyncTwinState",
			Handler:       _TwinControl_SyncTwinState_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pheromone/v1/twin_control.proto",
}
